require("bzip2")
require("xz")
require("zlib")
require("elfutils@source")

return recipe({
    build = [[
        cp -r $NESTDIR/source/elfutils/* .
        # Debuginfod is not reachable from a build machine; libelf is the part
        # of Elfutils that the rest of the system needs.
        #
        # configure needs argp and Bionic has none, so ./configure fails on
        # every Android and mingw target. configure.ac:651 does an
        # unconditional AC_SEARCH_LIBS([argp_parse],[argp]) with
        # AC_MSG_FAILURE at :654, at top level and not inside any AS_IF, and
        # elfutils 0.193 has no switch that could pre-set it: all 47
        # --enable/--disable/--with/--without options in ./configure --help
        # were enumerated and none drops libdw, libdwfl, libstack, libebl or
        # tests/ from SUBDIRS. argp is a glibc extension absent from Bionic at
        # every API level, so no new androidNN target changes it.
        #
        # That does NOT make libelf unbuildable, only configure. libelf
        # compiles standalone: it needs just $(top_builddir)/config.h, which
        # ./configure has already generated by the time it fails on a
        # target, and config/eu.am:34 supplies -I$(top_srcdir)/lib for
        # common.h and abstract.h. So the build below is scoped to libelf
        # and never descends into libdw, libdwfl, libstack, libbacktrace,
        # backends/ or the test suite. On a target, configure still aborts
        # before any of this runs - the libelf-only path is untested there.
        # What it does buy is that clang-native, the one system where
        # configure succeeds, stops compiling and discarding the whole tree.
        ./configure $AUTOCONF_CONFIGURE_FLAGS \
            --disable-debuginfod \
            --enable-libdebuginfod=dummy
        touch aclocal.m4 configure config.h.in
        find . -name 'Makefile.in' | xargs touch
        make -j1 -C libelf
        make -j1 -C libelf install
        mkdir -p $OUT/lib/pkgconfig
        cp config/libelf.pc $OUT/lib/pkgconfig/
    ]]
})
