require("file@source")

return recipe({
    build = [[
        cp -r $NESTDIR/source/file/* .
        ./configure $AUTOCONF_CONFIGURE_FLAGS
        touch aclocal.m4 configure config.h.in
        find . -name 'Makefile.in' | xargs touch
        # The magic database is generated by running file, so a cross build
        # needs file 5.46 of the same version on the build host.
        make -j1
        make -j1 install
    ]]
})
