require("glad@source")
-- GLAD2 has no build system at all: it is a Python package, and the C that
-- actually installs is whatever `python3 -m glad` writes out. The generator
-- therefore needs a HOST interpreter, which on every cross system is the one
-- in the native prefix: the loader puts $NATIVE_PREFIX/bin at the front of
-- PATH for every block, so a bare `python3` here is always the native one and
-- never the target's. The three requires are `@native` for that reason and
-- are the whole answer to "where does the generated source come from".
require("python@native")
-- The generator imports Jinja2 (glad/generator/__init__.py:6) and Jinja2
-- imports MarkupSafe. Both are pure-Python recipes in this tree - markupsafe
-- does not build its optional _speedups C accelerator and falls back to its
-- pure-Python module - so @native copies are architecture-independent and
-- land in the native interpreter's own site-packages, which is where it looks.
require("jinja2@native")
require("markupsafe@native")

return recipe({
    build = [[
        # --reproducible is load-bearing, not cosmetic. Without it the CLI
        # installs glad.opener.URLOpener and fetches gl.xml from
        # raw.githubusercontent.com (glad/__main__.py:149-153), which is
        # network access at build time and therefore forbidden here. With it
        # the CLI installs glad.files.StaticFileOpener, whose urlopen()
        # discards the URL and opens the same basename out of glad/files/
        # instead (glad/files/__init__.py:47-56). Every registry the GL
        # specification needs is vendored in the release - glad/files/ holds
        # gl.xml, egl.xml, glx.xml, wgl.xml, vk.xml, khrplatform.h and
        # eglplatform.h - so generation is fully offline, and it also pins the
        # timestamp to '-' so the output is byte-stable across runs.
        #
        # --api=gl:core=3.3,gles2 covers both halves of what these targets can
        # actually run: desktop GL for x86_64-mingw and clang-native, and
        # GLES2 for Android. No version means "latest", so both are pinned
        # explicitly. --loader emits glad's own dlopen-based loader
        # (templates/loader/*.c); without it the generated source declares
        # the function-pointer table but leaves gladLoadGLLoader() for the
        # consumer to implement, and there is no other loader in this prefix.
        #
        # Output layout is fixed by the generator, not by us: one header and
        # one source per API, named after the API (glad/parse.py:780), at
        # include/glad/<api>.h and src/<api>.c, plus any Khronos headers the
        # selected API pulls in (glad/generator/c/__init__.py:395-410).
        python3 -m glad --out-path=glad-out --reproducible --api=gl:core=3.3,gles2 --loader c
        mkdir -p obj $OUT/lib $OUT/include
        # The generated sources are plain C and include their own header by
        # the installed path (<glad/gl.h>, base_template.c:10), so they need
        # the generated include tree on the search path and nothing else -
        # no OpenGL headers, no X11, no EGL.
        $CC $CFLAGS -Iglad-out/include -c glad-out/src/gl.c -o obj/gl.o
        $CC $CFLAGS -Iglad-out/include -c glad-out/src/gles2.c -o obj/gles2.o
        $AR rcs $OUT/lib/libglad.a obj/gl.o obj/gles2.o
        $RANLIB $OUT/lib/libglad.a
        cp -r glad-out/include/. $OUT/include/
        # Upstream ships no .pc and no CMake package config anywhere in the
        # tree - this is a generator, it has nothing to describe - so one is
        # written here, as packages/lua/generic.lua does.
        mkdir -p $OUT/lib/pkgconfig
        cat > $OUT/lib/pkgconfig/glad.pc <<EOF
        prefix=$PREFIX
        exec_prefix=\${prefix}
        libdir=\${exec_prefix}/lib
        includedir=\${prefix}/include
        Name: glad
        Description: Multi-API GL/GLES/GLX/EGL loader generated by glad
        Version: 2.0.8
        Libs: -L\${libdir} -lglad
        Cflags: -I\${includedir}
        EOF
    ]]
})