#!/usr/bin/env python3
"""Embed a Lua file as a C string literal. Usage: embed.py <in.lua> <out.c>."""
import sys

src, dst = sys.argv[1], sys.argv[2]
with open(src, "rb") as f:
    data = f.read()

lines = ["/* Generated by embed.py; do not edit. Source: %s */" % src]
lines.append("const char *loader_lua =")
for raw in data.decode("utf-8").splitlines(keepends=True):
    if raw.endswith("\n"):
        body, nl = raw[:-1], "\\n"
    else:
        body, nl = raw, ""
    esc = (
        body.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("?", "\\?")  # avoid trigraphs
    )
    lines.append('  "%s%s"' % (esc, nl))
lines.append("  ;")
with open(dst, "w") as f:
    f.write("\n".join(lines) + "\n")
